apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-keaycloak.placesm-portfolio.fr
  namespace: auth
spec:
  secretName: my-keycloak.placesm-portfolio.fr-tls
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: my-keycloak.placesm-portfolio.fr
  dnsNames:
  - my-keycloak.placesm-portfolio.fr